export const products = [
  {
    id: 'one-love-white-longsleeve',
    name: 'ONE LOVE WHITE LONGSLEEVE',
    price: 85,
    collection: 'summer-26',
    color: 'White',
    material: '100% Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://placehold.co/800x1000/f5f5f5/333?text=ONE+LOVE+WHITE',
    ],
    thumbnail: 'https://placehold.co/400x500/f5f5f5/333?text=ONE+LOVE+WHITE',
    variants: ['White'],
    description: 'Long sleeve tee featuring colorful flame graphic prints down the sleeve. Relaxed fit with ribbed cuffs and collar.',
    features: ['Relaxed fit', 'Ribbed cuffs', 'Screen printed graphics', 'Pre-washed'],
    badge: null,
  },
  {
    id: 'beach-bum-yellow-longsleeve',
    name: 'BEACH BUM YELLOW LONGSLEEVE',
    price: 100,
    collection: 'summer-26',
    color: 'Yellow',
    material: '100% Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://placehold.co/800x1000/e8f500/111?text=BEACH+BUM+YELLOW',
    ],
    thumbnail: 'https://placehold.co/400x500/e8f500/111?text=BEACH+BUM+YELLOW',
    variants: ['Yellow', 'Red'],
    description: 'Sport-inspired longsleeve with contrast raglan sleeves and bold TWOJEYS chest logo. Boxy cropped fit.',
    features: ['Cropped boxy fit', 'Contrast raglan sleeves', 'Woven label at hem', 'Mediterranean West Coast patch'],
    badge: null,
  },
  {
    id: 'beach-bum-red-longsleeve',
    name: 'BEACH BUM RED LONGSLEEVE',
    price: 100,
    collection: 'summer-26',
    color: 'Red',
    material: '100% Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://placehold.co/800x1000/ff3c2a/fff?text=BEACH+BUM+RED',
      'https://placehold.co/800x1000/ff3c2a/fff?text=BACK+VIEW',
      'https://placehold.co/800x1000/ff3c2a/fff?text=DETAIL',
      'https://placehold.co/800x1000/ff3c2a/fff?text=ON+MODEL',
      'https://placehold.co/800x1000/ff3c2a/fff?text=STYLED',
    ],
    thumbnail: 'https://placehold.co/400x500/ff3c2a/fff?text=BEACH+BUM+RED',
    variants: ['Red', 'Yellow'],
    description: 'Sport-inspired longsleeve with contrast cream raglan sleeves and bold TWOJEYS chest logo. Boxy cropped fit with contrast topstitching throughout.',
    features: ['Cropped boxy fit', 'Contrast cream raglan sleeves', 'Contrast topstitching', 'Woven label at hem', 'Mediterranean West Coast woven patch'],
    badge: null,
  },
  {
    id: 'twojeys-sleeveless-varsity-tee',
    name: 'TWOJEYS SLEEVELESS VARSITY TEE',
    price: 60,
    collection: 'summer-26',
    color: 'Grey',
    material: '100% Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://placehold.co/800x1000/d8d8d8/333?text=SLEEVELESS+VARSITY',
    ],
    thumbnail: 'https://placehold.co/400x500/d8d8d8/333?text=SLEEVELESS+VARSITY',
    variants: ['Grey'],
    description: 'Relaxed sleeveless tee with small double star logo embroidered on chest. Clean minimal design.',
    features: ['Relaxed fit', 'Sleeveless', 'Embroidered logo', 'Raw hem'],
    badge: null,
  },
  {
    id: 'twilight-white-tee',
    name: 'TWILIGHT WHITE TEE',
    price: 65,
    collection: 'summer-26',
    color: 'Charcoal',
    material: '100% Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://placehold.co/800x1000/3a3a3a/fff?text=TWILIGHT+TEE',
    ],
    thumbnail: 'https://placehold.co/400x500/3a3a3a/fff?text=TWILIGHT+TEE',
    variants: ['Charcoal'],
    description: 'Garment-dyed tee with small flame logo embroidered on chest. Heavy-weight cotton with a broken-in feel.',
    features: ['Oversized fit', 'Garment dyed', 'Heavy-weight cotton', 'Embroidered logo'],
    badge: null,
  },
  {
    id: 'twojeys-blue-tee',
    name: 'TWOJEYS BLUE TEE',
    price: 70,
    collection: 'summer-26',
    color: 'Blue',
    material: '100% Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://placehold.co/800x1000/1a4fd6/fff?text=TWOJEYS+BLUE+TEE',
    ],
    thumbnail: 'https://placehold.co/400x500/1a4fd6/fff?text=TWOJEYS+BLUE+TEE',
    variants: ['Blue'],
    description: 'Bold cobalt blue tee with large oval TWOJEYS logo print on chest. Statement piece for summer.',
    features: ['Regular fit', 'Screen printed logo', 'Pre-washed', 'Ribbed collar'],
    badge: null,
  },
]

export const getProductById = (id) => products.find(p => p.id === id)
export const getProductsByCollection = (collection) => products.filter(p => p.collection === collection)
